(require 'calendar)
(require 'solar)
(require 'lunar)
(require 'cl-lib)
(require 'cal-julian)

; Output from this code matches that of Python code (sayana-panchanga.py) exactly!
; This code is generated by Google Gemini and slightly adapted
; Also matches the output in Dieter Koch's https://www.gilgamesh.ch/kalender/kalender.html

(defconst solar-rasis '("Mesha" "Vrishabha" "Mithuna" "Karka" "Simha"
  "Kanya" "Tula" "Vrishchika" "Dhanus" "Makara" "Kumbha" "Meena"))

(defun get-solar-longitude (gregorian-date ut-hour &optional sidereal-p)
  "Get true ecliptic longitude for a Gregorian DATE (month day year) and UT hour.
If SIDEREAL-P is non-nil, returns Nirayana (sidereal) longitude using Lahiri Ayanamsha.
Otherwise, returns Sayana (tropical) longitude."
  (let* ((julian-centuries (solar-date-to-et gregorian-date ut-hour))
         (coords (solar-ecliptic-coordinates julian-centuries t))
         (tropical-long (car coords)))
    (if sidereal-p
        ;; Apply linear approximation of Lahiri Ayanamsha
        ;; Base Ayanamsha at J2000.0 (Jan 1, 2000) is ~23.85°
        ;; Average rate of precession is ~1.39604° per Julian century
        (let* ((ayanamsha (+ 23.85709 (* julian-centuries 1.39604)))
               (sidereal-long (- tropical-long ayanamsha)))
          (mod sidereal-long 360.0))
      (mod tropical-long 360.0))))

(defun calculate-gregorian-from-solar (year month-name solar-day &optional sidereal-p)
  "Convert a Sayana or Nirayana solar date to a Gregorian date.
YEAR is the primary Gregorian year of the cycle.
MONTH-NAME is the solar Rasi (e.g., \"Mesha\").
SOLAR-DAY is the integer day of the solar month.
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15)

; Example execution (Nirayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15 t)
"
  (let* ((target-rasi-idx (cl-position month-name solar-rasis :test 'string=))
         ;; Determine safe search start date (absorbs both Sayana and Nirayana variance)
         ;; (1-2 months before expected Sankranti)
         (start-month (nth target-rasi-idx '(2 3 4 5 6 7 8 9 10 11 12 1)))
         ;; Kumbha (idx 10) occurs early in the year, so we start searching in Dec of the prior year.
         (start-year (if (= target-rasi-idx 10) (1- year) year))
         (current-abs (calendar-absolute-from-gregorian (list start-month 1 start-year))))

    (unless target-rasi-idx
      (error "Invalid solar month name: %s" month-name))

    ;; Step forward until 00:00 UT falls into the target Rasi
    (while (/= (floor (/ (get-solar-longitude
                          (calendar-gregorian-from-absolute current-abs)
                          0.0    ;; midnight-to-midnight
                          sidereal-p)
                         30.0))  ;; Each rasi spans 30°
               target-rasi-idx)
      (setq current-abs (1+ current-abs)))

    ;; Apply the Day 1 offset
    ;; If the sun is in the target Rasi at 00:00 UT on current-abs,
    ;; the transition (Sankranti) occurred on the previous day.
    (let* ((day-one (1- current-abs))
           (target-abs (+ day-one (1- solar-day)))
           (result-greg (calendar-gregorian-from-absolute target-abs))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

  (message "%s Input: %s %d, %04d | Gregorian Result: %04d-%02d-%02d"
           system-name month-name solar-day year
           (nth 2 result-greg) (nth 0 result-greg) (nth 1 result-greg)))))

(defun calculate-solar-from-gregorian (year month day fallback-ut &optional sidereal-p)
  "Calculate the Sayana or Nirayana month and day for a Gregorian date and UT time.
Evaluates solar longitude at the exact moment of local sunrise (defaults to Ujjain).
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-solar-from-gregorian 2026 3 17 14.0)

Example execution (Nirayana):
(calculate-solar-from-gregorian 2026 3 17 14.0 t)
"
  (let* ((gregorian-date (list month day year))
         (target-abs-date (calendar-absolute-from-gregorian gregorian-date))

         ;; 1. Fetch Sunrise UT
         (target-ut-hour (get-sunrise-ut gregorian-date fallback-ut))

         ;; 2. Get current longitude at sunrise and determine the Rasi index
         (current-long (get-solar-longitude gregorian-date target-ut-hour sidereal-p))
         (target-rasi-idx (floor (/ current-long 30.0)))

         ;; 3. Search backward at sunrise each day to find the Sankranti transition
         (sankranti-abs-date target-abs-date)
         ;; Increased search limit to 35 safely covers maximum Nirayana month length
         ;; Though a tropical solar month is normally 29-32 days
         (search-limit (- target-abs-date 35)))

    (while (and (> sankranti-abs-date search-limit)
                (let* ((test-greg (calendar-gregorian-from-absolute sankranti-abs-date))
                       (test-ut (get-sunrise-ut test-greg fallback-ut))
                       (test-long (get-solar-longitude test-greg test-ut sidereal-p)))
                  (= (floor (/ test-long 30.0)) target-rasi-idx))) ; one rasi is 30 degrees
      (setq sankranti-abs-date (1- sankranti-abs-date)))

    ;; 4. Calculate the day (Sankranti day itself is Day 1)
    (let* ((day-one sankranti-abs-date)
           (solar-day (1+ (- target-abs-date day-one)))
           (rasi-name (nth target-rasi-idx solar-rasis))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

      (message "%s | Date: %04d-%02d-%02d | Sunrise UT: %.2f | %s %d | Longitude: %.2f°"
               system-name year month day target-ut-hour
               rasi-name solar-day
               current-long))))


(require 'lunar)

(defconst lunar-months '("Vaisakha" "Jyeshtha" "Ashadha" "Shravana"
  "Bhadrapada" "Ashvina" "Kartika" "Margashirsha" "Pausha" "Magha"
  "Phalguna" "Chaitra"))

(defun get-sunrise-ut (gregorian-date fallback-ut)
  "Calculate sunrise in UT for GREGORIAN-DATE using Emacs location settings.
Defaults to Ujjain, India if calendar coordinates are unset.
Falls back to FALLBACK-UT if no sunrise exists (e.g., polar night/day)."
  (let* ((calendar-latitude (if (bound-and-true-p calendar-latitude)
                                calendar-latitude
                              23.1765))
         (calendar-longitude (if (bound-and-true-p calendar-longitude)
                                 calendar-longitude
                               75.7885))
         (calendar-time-zone (if (bound-and-true-p calendar-time-zone)
                                 calendar-time-zone
                               330)) ; +5:30 IST in minutes

         (sun-data (solar-sunrise-sunset gregorian-date))
         (sunrise-local (and sun-data (car (car sun-data)))))

    (if (numberp sunrise-local)
        (- sunrise-local (/ calendar-time-zone 60.0))
      fallback-ut)))


(defun calculate-lunar-from-gregorian (year month day fallback-ut &optional sidereal-p)
  "Calculate the traditional lunar month, Paksha, and Madhyama Tithi at local sunrise.
Uses `lunar-new-moon-on-or-after' with Julian Day conversions for precise bounding.
If SIDEREAL-P is non-nil, calculates using Nirayana solar longitude."
  (let* ((target-date (list month day year))
         (target-abs (calendar-absolute-from-gregorian target-date))

         ;; 1. Fetch Sunrise UT and convert target to Julian Day
         (target-ut-hour (get-sunrise-ut target-date fallback-ut))
         (target-abs-time (+ target-abs (/ target-ut-hour 24.0)))
         (target-jd (calendar-astro-from-absolute target-abs-time))

         ;; 2. Find the bounding New Moons in Julian Days
         (prev-nm-jd (lunar-new-moon-on-or-after (- target-jd 35.0)))
         (next-nm-jd (lunar-new-moon-on-or-after (+ prev-nm-jd 1.0))))

    ;; Bracket the target time precisely
    (while (<= next-nm-jd target-jd)
      (setq prev-nm-jd next-nm-jd)
      (setq next-nm-jd (lunar-new-moon-on-or-after (+ prev-nm-jd 1.0))))

    ;; 3. Convert boundaries back to Emacs Absolute Time
    (let* ((prev-nm (calendar-astro-to-absolute prev-nm-jd))
           (next-nm (calendar-astro-to-absolute next-nm-jd))

           ;; 4. Calculate Madhyama Tithi and Paksha
           (cycle-length (- next-nm prev-nm))
           (tithi-length (/ cycle-length 30.0))
           (elapsed (- target-abs-time prev-nm))
           (tithi-idx (1+ (floor (/ elapsed tithi-length))))
           (paksha (if (<= tithi-idx 15) "Shukla" "Krishna"))
           (tithi-num (if (> tithi-idx 15) (- tithi-idx 15) tithi-idx))

           ;; 5. Evaluate Sun's longitude at both New Moon boundaries
           (nm1-abs-date (truncate prev-nm))
           (nm1-ut-hour (* (- prev-nm nm1-abs-date) 24.0))
           (nm1-greg-date (calendar-gregorian-from-absolute nm1-abs-date))
           (sun-long-start (get-solar-longitude nm1-greg-date nm1-ut-hour sidereal-p))

           (nm2-abs-date (truncate next-nm))
           (nm2-ut-hour (* (- next-nm nm2-abs-date) 24.0))
           (nm2-greg-date (calendar-gregorian-from-absolute nm2-abs-date))
           (sun-long-end (get-solar-longitude nm2-greg-date nm2-ut-hour sidereal-p))

           ;; 6. Determine Lunar Month and Adhika flag
           (rasi-idx-start (floor (/ sun-long-start 30.0)))
           (rasi-idx-end (floor (/ sun-long-end 30.0)))
           (is-adhika (= rasi-idx-start rasi-idx-end))

           (base-month-name (nth rasi-idx-start lunar-months))
           (lunar-month-name (if is-adhika
                                 (concat "Adhika " base-month-name)
                               base-month-name))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

      (message "%s | Date: %04d-%02d-%02d | Sunrise UT: %.2f | %s %s %d"
               system-name year month day target-ut-hour
               lunar-month-name paksha tithi-num))))
