from nakshatra_table import print_nakshatra_table

candidates = [
    ",41Ari", #"Bharani",
    "Botein",
    "Hamal",
    "Mesarthim",
    "Sheratan",
    "Ain",
    "Alcyone",
    "Aldebaran",
    "Asterope",
    "Atlas",
    ",16Tau", #"Celaeno",
    ",th-2Tau", #"Chamukuy",
    "Electra",
    "Elnath",
    # "Hoggar",
    "Maia",
    "Merope",
    "Pleione",
    "Prima Hyadum",
    "Secunda Hyadum",
    "Taygeta",
    ",zeTau", #"Tianguan",
    "Alhena",
    "Alzirr",
    "Castor",
    # "Jishui", # 4.89 mag
    "Mebsuta",
    "Mekbuda",
    "Pollux",
    "Propus",
    "Tejat",
    "Wasat",
    "Acubens",
    "Asellus Australis",
    "Asellus Borealis",
    # "Copernicus", # 5.95 mag
    # "Gakyid", # mag 8.23
    # "Meleph", # mag 6.29
    ",xiCnc", # "Nahn",
    # "Piautos", # mag 5.92
    ",beCnc", # "Tarf",
    "Tegmine",
    "Adhafera",
    "Algieba",
    "Alterf",
    "Chertan",
    "Denebola",
    # "Dingolay",
    # "Formosa",
    "Rasalas",
    "Regulus",
    # "Sagarmatha",
    # "Shama",
    "Subra",
    "Zosma",
    ",phVir", #"Elgafar",
    # "Flegetonte",
    "Heze",
    ",kaVir", # "Kang",
    "Khambalia",
    # "Lich",
    # "Malmok",
    ",deVir", #"Minelauva",
    # "Monch",
    "Porrima",
    "Spica",
    "Syrma",
    "Vindemiatrix",
    "Zaniah",
    "Zavijava",
    "Brachium",
    "Zubenelgenubi",
    ",gaLib", #"Zubenelhakrabi",
    ",beLib", #"Zubeneschamali",
    "Acrab",
    "Alniyat",
    "Antares",
    # "Diwo",
    "Dschubba",
    ",piSco", # "Fang",
    # "Fuyue", # mag 3.19 # 
    ",rhSco", # "Iklil",
    "Jabbah",
    ",epSco", #"Larawag",
    "Lesath",
    ",taSco", # Paikauhale",
    # "Pipirima", # mag 3.56
    # "Rapeto", # mag 7
    "Sargas",
    #"Sharjah", # mag 11
    "Shaula",
    ",mu-1Sco", # "Xamidimura",
    ",nu-1Sgr", #"Ainalrami",
    "Albaldah",
    "Alnasl",
    "Arkab Posterior",
    "Arkab Prior",
    "Ascella",
    # "Belel", # mag 7.5
    # "Gumala", # mag 6.25
    "Kaus Australis",
    "Kaus Borealis",
    ",deSgr", #"Kaus Media",
    "Nunki",
    # "Pincoya",
    "Polis",
    "Rukbat",
    # "Sika",
    ",omeSgr", #"Terebellum",
    "Algedi",
    "Alshat",
    "Dabih",
    "Deneb Algedi",
    "Nashira",
    ",epCap", #"Albali", or "Castra"    
    ",thCap", # "Ancha", or orsum
    # "Bosona",
    "Bunda", # xiAgr mag 4.80
    # "Lionrock",
    # "Marohu",
    ",gaAqr", # "Sadachbia",
    "Sadalmelik",
    "Sadalsuud",
    "Situla",
    "Skat",
    "Hydor",
    ",etPsc", #"Alpherg",
    ",alPsc", #"Alrescha",
    # "Belenos",
    # "Citadelle",
    # "Ebla",
    ",bePsc", #"Fumalsamakah",
    # "Parumleo",
    ",zePsc", #"Revati",
    ",omiPsc", # "Torcular ",
]

print("| Name | Bayer | Lat° | Long° | Motion |")
print("|:-----|:------|:-----|:------|:-------|")
print_nakshatra_table(candidates)
