"""Generic policy vocabulary, assignments, and timing constants."""

from .catalog import (
    AKSAYA_TRTIYA_NUMBER,
    BALI_PADYAMI_NUMBER,
    DEEPAVALI_NUMBER,
    DHANA_TRAYODASHI_NUMBER,
    GANESHA_CATURTHI_NUMBER,
    JANMASHTAMI_NUMBER,
    KAMA_DAHANA_NUMBER,
    MAHA_SHIVARATRI_NUMBER,
    MAHALAYA_AMAVASYA_NUMBER,
    MAHANAVAMI_PUJA_NUMBER,
    NARAKA_CHATURDASHI_NUMBER,
    NARASIMHA_JAYANTI_NUMBER,
    RAKSHA_BANDHAN_NUMBER,
    RAMA_NAVAMI_NUMBER,
    RATHA_SAPTAMI_NUMBER,
    RIG_UPAKARMA_NUMBER,
    UGADI_NUMBER,
    VASANTA_PANCHAMI_NUMBER,
    VIJAYA_DASAMI_NUMBER,
    YAJUR_UPAKARMA_NUMBER,
)
from .model import GenericKalaValidityOverlay


PRATAH_KALA = "pratah"
SANGAVA_KALA = "sangava"
PURVAHNA_KALA = "purvahna"
MADHYAHNA_KALA = "madhyahna"
APARAHNA_KALA = "aparahna"
SAYAHNA_KALA = "sayahna"
SUNSET_KALA = "sunset"
PRADOSHA_KALA = "pradosha"
PURVARATRI_KALA = "purvaratri"
MADHYARATRI_KALA = "madhyaratri"
GADHARATRI_KALA = "gadharatri"
ARUNODAYA_KALA = "arunodaya"
RATRI_KALA = MADHYARATRI_KALA
PURVODAYA_KALA = ARUNODAYA_KALA
SUNRISE_KALA = "sunrise"
NIGHT_KALAS = {
    PRADOSHA_KALA,
    PURVARATRI_KALA,
    MADHYARATRI_KALA,
    GADHARATRI_KALA,
}

GENERIC_KALA_BY_FESTIVAL = {
    UGADI_NUMBER: SUNRISE_KALA,
    RIG_UPAKARMA_NUMBER: PURVAHNA_KALA,
    VASANTA_PANCHAMI_NUMBER: PURVAHNA_KALA,
    RAMA_NAVAMI_NUMBER: MADHYAHNA_KALA,
    AKSAYA_TRTIYA_NUMBER: MADHYAHNA_KALA,
    GANESHA_CATURTHI_NUMBER: MADHYAHNA_KALA,
    BALI_PADYAMI_NUMBER: MADHYAHNA_KALA,
    RAKSHA_BANDHAN_NUMBER: APARAHNA_KALA,
    MAHALAYA_AMAVASYA_NUMBER: APARAHNA_KALA,
    MAHANAVAMI_PUJA_NUMBER: APARAHNA_KALA,
    VIJAYA_DASAMI_NUMBER: APARAHNA_KALA,
    NARASIMHA_JAYANTI_NUMBER: SUNSET_KALA,
    DHANA_TRAYODASHI_NUMBER: PRADOSHA_KALA,
    DEEPAVALI_NUMBER: PRADOSHA_KALA,
    KAMA_DAHANA_NUMBER: PRADOSHA_KALA,
    JANMASHTAMI_NUMBER: MADHYARATRI_KALA,
    MAHA_SHIVARATRI_NUMBER: MADHYARATRI_KALA,
    NARAKA_CHATURDASHI_NUMBER: ARUNODAYA_KALA,
    RATHA_SAPTAMI_NUMBER: ARUNODAYA_KALA,
}

UPAKARMA_CONTAMINATION_VALIDATOR = "upakarma-contamination"
GENERIC_VALIDITY_BY_FESTIVAL = {
    YAJUR_UPAKARMA_NUMBER: GenericKalaValidityOverlay(
        UPAKARMA_CONTAMINATION_VALIDATOR,
        fallback_masa_offset=1,
    ),
}
# Compatibility name retained for callers written before the overlay became
# shared by the Midpoint, Anchor, and Kala policies.
GENERIC_KALA_VALIDITY_BY_FESTIVAL = GENERIC_VALIDITY_BY_FESTIVAL
GENERIC_KALA_NAME_BY_FESTIVAL = {
    JANMASHTAMI_NUMBER: "Janmashtami (Madhyaratri Kala)",
}

SUNRISE_ANCHOR = "sunrise"
DAY_MIDPOINT_ANCHOR = "day-midpoint"
SUNSET_ANCHOR = "sunset"
NIGHT_MIDPOINT_ANCHOR = "night-midpoint"
DAY_FIRST_QUARTER_ANCHOR = "day-first-quarter"
DAY_THIRD_QUARTER_ANCHOR = "day-third-quarter"
NIGHT_FIRST_QUARTER_ANCHOR = "night-first-quarter"
NIGHT_THIRD_QUARTER_ANCHOR = "night-third-quarter"
GENERIC_ANCHOR_BY_FESTIVAL = {
    UGADI_NUMBER: SUNRISE_ANCHOR,
    YAJUR_UPAKARMA_NUMBER: SUNRISE_ANCHOR,
    RIG_UPAKARMA_NUMBER: DAY_FIRST_QUARTER_ANCHOR,
    VASANTA_PANCHAMI_NUMBER: DAY_FIRST_QUARTER_ANCHOR,
    RAMA_NAVAMI_NUMBER: DAY_MIDPOINT_ANCHOR,
    AKSAYA_TRTIYA_NUMBER: DAY_MIDPOINT_ANCHOR,
    GANESHA_CATURTHI_NUMBER: DAY_MIDPOINT_ANCHOR,
    BALI_PADYAMI_NUMBER: DAY_MIDPOINT_ANCHOR,
    RAKSHA_BANDHAN_NUMBER: DAY_THIRD_QUARTER_ANCHOR,
    MAHALAYA_AMAVASYA_NUMBER: DAY_THIRD_QUARTER_ANCHOR,
    MAHANAVAMI_PUJA_NUMBER: DAY_THIRD_QUARTER_ANCHOR,
    VIJAYA_DASAMI_NUMBER: DAY_THIRD_QUARTER_ANCHOR,
    NARASIMHA_JAYANTI_NUMBER: SUNSET_ANCHOR,
    DHANA_TRAYODASHI_NUMBER: NIGHT_FIRST_QUARTER_ANCHOR,
    DEEPAVALI_NUMBER: NIGHT_FIRST_QUARTER_ANCHOR,
    KAMA_DAHANA_NUMBER: NIGHT_FIRST_QUARTER_ANCHOR,
    JANMASHTAMI_NUMBER: NIGHT_MIDPOINT_ANCHOR,
    MAHA_SHIVARATRI_NUMBER: NIGHT_MIDPOINT_ANCHOR,
    NARAKA_CHATURDASHI_NUMBER: NIGHT_THIRD_QUARTER_ANCHOR,
    RATHA_SAPTAMI_NUMBER: NIGHT_THIRD_QUARTER_ANCHOR,
}
GENERIC_ANCHOR_NAME_BY_FESTIVAL = {
    JANMASHTAMI_NUMBER: "Janmashtami (Ratri Anchor)",
}

ONE_GHATI_HOURS = 24 / 60
SIX_GHATI_HOURS = 6 * ONE_GHATI_HOURS
ARUNODAYA_HOURS = 4 * ONE_GHATI_HOURS
PRADOSHA_HOURS = 6 * ONE_GHATI_HOURS
